module.exports = {
    "IPA": "first, boil water.  then make the beer.  easy!",
    "Belgian Wit Beer": "no problem.  get your ingredients together.  start off by boiling water.  hit your grains with 170 degree water, to attain a target mash temperature of 150 degrees.  let the grains mash for an hour, before sparging.  sparge with 180 degree water to keep the grains geletanized.  after the wort is brought up to a boil, add your hops and boil per the schedule.  chill the wort and ferment with your yeast of choice for two weeks.  bottle with 1 gram of corn sugar per gallon.",
    "Pale ale": "start by mashing the grains in 150 degree water.  after an hour, sparge with 180 degree water.  boil the wort for an hour with the hops of your choice.  chill the wort and add the yeast.  now the hard part: wait two weeks before bottling.  enjoy!",
    "Stout": "first, boil water.  then make the beer.  easy!",
    "belgian saison": "no problem.  get your ingredients together.  start off by boiling water.  hit your grains with 170 degree water, to attain a target mash temperature of 150 degrees.  let the grains mash for an hour, before sparging.  sparge with 180 degree water to keep the grains geletanized.  after the wort is brought up to a boil, add your hops and boil per the schedule.  chill the wort and ferment with your yeast of choice for two weeks.  bottle with 1 gram of corn sugar per gallon.",
    "blonde ale": "first, boil water.  then make the beer.  easy!",
    "brown ale": "no problem.  get your ingredients together.  start off by boiling water.  hit your grains with 170 degree water, to attain a target mash temperature of 150 degrees.  let the grains mash for an hour, before sparging.  sparge with 180 degree water to keep the grains geletanized.  after the wort is brought up to a boil, add your hops and boil per the schedule.  chill the wort and ferment with your yeast of choice for two weeks.  bottle with 1 gram of corn sugar per gallon.",
    "porter": "first, boil water.  then make the beer.  easy!",
    "hefeweisen": "no problem.  get your ingredients together.  start off by boiling water.  hit your grains with 170 degree water, to attain a target mash temperature of 150 degrees.  let the grains mash for an hour, before sparging.  sparge with 180 degree water to keep the grains geletanized.  after the wort is brought up to a boil, add your hops and boil per the schedule.  chill the wort and ferment with your yeast of choice for two weeks.  bottle with 1 gram of corn sugar per gallon.",
    "lager": "first, boil water.  then make the beer.  easy!"
};
